---
- name: BigPanda Webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  rules:
    - name: Get BigPanda Share Information
      condition: event.meta is defined
      action:
        debug:
        